Add issue templates
prophesee-ai/openeb pull request #23
Opened 2021-09-29 05:47 UTC by laurentbristiel

2021-09-29 08:25 UTC, nbourdis-psee commented on .github/ISSUE_TEMPLATE/bug_report.md
> +* software that has an issue, expected and actual behavior, and as detailed as possible reproduction steps
```suggestion
* software that has an issue, expected and actual behavior, and reproduction steps as detailed as possible 
```

2021-09-29 08:25 UTC, nbourdis-psee commented on .github/ISSUE_TEMPLATE/bug_report.md
> +
Should we add an item about sharing of RAW recordings, to enable reproducing the results on our side?

2021-09-29 11:11 UTC, KingArrkinian requested changes

2021-09-30 17:31 UTC, laurentbristiel commented on .github/ISSUE_TEMPLATE/bug_report.md
> +If you are a Metavision Professional customer, you are also granted access to our personal support and our Knowledge Center. Contact us via support@prophesee.ai
I would prefer to keep it at the bottom. Putting it in the beginning is putting too much emphasis on the MetavisionPro/OpenEB split which many people should not have to care about.

2021-09-30 19:16 UTC, KingArrkinian approved these changes

2021-10-01 06:22 UTC, cbernard-psee approved these changes

2021-10-01 06:28 UTC, nbourdis-psee approved these changes

2021-10-01 07:00 UTC, merged